---
- name: Server1
  hosts: server1
  become: yes
  gather_facts: false
  tasks:
  - name: This is pretty much filler space since the vagrantfile calls upon it
    debug:
      msg: "Hello, is it this file you're looking for? I can see it in your eyes. I can see it in your smile."
