---
- name: Server1
  hosts: server1
  become: yes
  tasks:
  - name: This is pretty much filler space since the vagrantfile calls upon it
    debug:
      msg: "Hello, is it this file you're looking for? I can see it in your eyes. I can see it in your smile."
  - name: Disable Vboxadd for faster boot
    service:
      name: vboxadd
      state: stopped
      enabled: no
  - name: Set Default target to multi-user 
    file:
      src: /usr/lib/systemd/system/multi-user.target
      dest: /etc/systemd/system/default.target
      state: link
  - name: Create folder for next play
    file:
      owner: vagrant
      group: vagrant
      path: /run/user/1000/containers
      state: directory
  - name: Copy auth.json to containers folder
    copy:
      src: /vagrant/auth.json
      dest: /run/user/1000/containers/auth.json
      owner: vagrant
      group: vagrant
  - name: Reboot for multi-user mode
    reboot:
      reboot_timeout: 1
    ignore_errors: true
