---
- name: Configure Server2
  become: true
  hosts: server2
  tasks:
  - name: Enable Firewall
    service:
      name: firewalld
      state: started
      enabled: yes 
  - name: Disable Vboxadd for faster boot
    service:
      name: vboxadd
      state: stopped
      enabled: no
  - name: Set Default target to multi-user 
    file:
      src: /usr/lib/systemd/system/multi-user.target
      dest: /etc/systemd/system/default.target
      state: link
#  - name: Delete eth0 connection
#    file:
#      path: /etc/sysconfig/network-scripts/ifcfg-eth0
#      state: absent
  - name: Reboot for multi-user mode
    reboot:
      reboot_timeout: 1
    ignore_errors: true
