---
- name: Server1
  hosts: server1
  become: yes
  tasks:
  - name: This is pretty much filler space since the vagrantfile calls upon it
    debug:
      msg: "Hello, is it this file you're looking for? I can see it in your eyes. I can see it in your smile."
  - name: Disable Vboxadd for faster boot
    service:
      name: vboxadd
      state: stopped
      enabled: no
  - name: Set Default target to multi-user 
    file:
      src: /usr/lib/systemd/system/multi-user.target
      dest: /etc/systemd/system/default.target
      state: link
  - name: Add stuff to the /etc/hosts file
    template:
      src: hosts.j2
      dest: /etc/hosts
    become: true
  - name: Reboot for multi-user mode
    reboot:
      reboot_timeout: 1
    ignore_errors: true
