---
- name: configure workstation
  gather_facts: false
  hosts: localhost
  become: false
  tasks:
  - name: Add stuff to the /etc/hosts file
    template:
      src: hosts.j2
      dest: /etc/hosts
    become: true
  - name: Copy Studyguides into homedir
    copy:
      src: /vagrant/StudyGuides
      dest: /home/vagrant/
      owner: vagrant
      group: vagrant
  - name: Make files executable
    file:
      path: "{{ item }}"
      owner: vagrant
      group: vagrant
      mode: +x
    loop:
      - /home/vagrant/StudyGuides/OuterLimits.sh
      - /home/vagrant/StudyGuides/TailsFromTheScript.sh
      - /home/vagrant/StudyGuides/podman.sh
