---
- name: configure workstation
  gather_facts: false
  hosts: localhost
  become: true
  tasks:
  - name: Change Locale
    lineinfile:
      path: /etc/locale.conf
      state: present
      regexp: ^LANG
      line: LANG=en_US.UTF-8
  - name: Add stuff to the /etc/hosts file
    template:
      src: hosts.j2
      dest: /etc/hosts
      
