---
- name: configure workstation
  gather_facts: false
  hosts: localhost
  become: false
  tasks:
  - name: Add stuff to the /etc/hosts file
    template:
      src: hosts.j2
      dest: /etc/hosts
    become: true

